###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: lihuamao_admin
  ####consul注册中心地址
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        #hostname: 127.0.0.1
#        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/lihuamao?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.bestlmc.lihuamao.commons.been    # 所有Entity别名类所在包
